// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUCqDmBW-JUEoBMCuOv_0xu1FFPsp2DmA',
    appId: '1:259026585807:web:34fc1e7677b23421d74fba',
    messagingSenderId: '259026585807',
    projectId: 'my-firebase-6b68b',
    authDomain: 'my-firebase-6b68b.firebaseapp.com',
    storageBucket: 'my-firebase-6b68b.firebasestorage.app',
    measurementId: 'G-958L3VP5Y8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjtsuurNyOPV1TKTC5RwjSyVl1Z3gIVrg',
    appId: '1:259026585807:android:c3c8f45aac455028d74fba',
    messagingSenderId: '259026585807',
    projectId: 'my-firebase-6b68b',
    storageBucket: 'my-firebase-6b68b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc6el2p8KDmIYfi2N7EpP9nD55rpIdUVo',
    appId: '1:259026585807:ios:20777153cb058c3ed74fba',
    messagingSenderId: '259026585807',
    projectId: 'my-firebase-6b68b',
    storageBucket: 'my-firebase-6b68b.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );
}
